### ISSUE TITLE
Feedback from 15/01 tracker dpg

### ISSUE THREAD

**Issue by OlivierBondu** [OlivierBondu/HIPAnalysis#3]
- [ ] map run number to actual date/time/run era
- [x] check saturation definition
- [ ] map lumi (=LS) to actual instantaneous luminosity
- [ ] normalize by nEvents ?
- [x] vary nSaturatedStrips to define nSaturatedClusters
- [ ] pick up bunch crossing information / filling scheme / bunch structure
- [ ] add cluster charge
- [ ] add nTracks
- [x] check what lumi actually is
- [x] charge / length as a function of BX
